buslog:
  image:
    tag: main-231fdcf
    repository: docker.io/aperturesci/buslog
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 100
ctrlr:
  image:
    tag: main-4dc9802
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 120s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
flask-ui:
  image:
    tag: main-07994b6
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
