buslog:
  image:
    tag: main-24c2191
    repository: docker.io/aperturesci/buslog
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 10s
          - setWeight: 100
ctrlr:
  image:
    tag: main-87aa2d5
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
          - setWeight: 100
flask-ui:
  image:
    tag: main-54bb50b
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
          - setWeight: 100
