buslog:
  image:
    tag: main-83eb5df
    repository: docker.io/aperturesci/buslog
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 100
ctrlr:
  image:
    tag: main-a7b90ab
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 120s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
flask-ui:
  image:
    tag: main-f161381
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 512s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
