buslog:
  image:
    tag: main-e62ecb2
    repository: docker.io/aperturesci/buslog
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 100
ctrlr:
  image:
    tag: main-f9c3b0e
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
flask-ui:
  image:
    tag: main-71680de
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 5s
          - setWeight: 50
          - pause:
              duration: 5s
          - setWeight: 100
