buslog:
  image:
    tag: main-e11282a
    repository: docker.io/aperturesci/buslog
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 10s
          - setWeight: 100
ctrlr:
  image:
    tag: main-d3eac54
    repository: docker.io/aperturesci/ctrlr
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
          - setWeight: 100
flask-ui:
  image:
    tag: main-4c68267
    repository: docker.io/aperturesci/flask-ui
  replicaCount: 3
  rollout:
    strategy:
      canary:
        steps:
          - setWeight: 20
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
          - setWeight: 100
